<?php

namespace ApiBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByNameLike($name)
    {
        $repo = $this->getDoctrine()->getManager()->getRepository('ApiBundle:City');

        return $repo->createQueryBuilder('c')
            ->where('c.name LIKE :name')
            ->setParameter('name', $name);
    }
}
